name: Lint docs

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - '**.md'
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - '**.md'
jobs:
  lint:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: articulate/actions-markdownlint@v1
        with:
          config: .github/workflows/markdownlint-config.json
          ignore: autopilot
